### ISSUE TITLE
Update the docs?

### ISSUE THREAD

**Issue by IstoraMandiri** [enjikaka/WaveformGenerator.js#4]
Hi, just found your lib and noticed your readme looks outdated -- you are using promises now right?

**Comment by enjikaka** [comment]
Hello! Yes, they are to be updated. I might be able to do that tonight. Thanks for the reminder!

**Comment by enjikaka** [comment]
You can check out this pen on Codepen to see how to use the new verison until I've updated the docs. 

http://codepen.io/enjikaka/full/DrFEk/

```
    var reader = new FileReader();
    reader.onload = function(event) {
        var settings = {
          bar: {
            align:'center', 
            width: 1, 
            gap: 0
          },
          waveform: {
            color: 'blue',
            width: 500,
            height: 80
          }
      };
      new WaveformGenerator(event.target.result, settings).then(function(s) {
        document.querySelector('.wave').innerHTML = s;
      });
    };
    reader.readAsArrayBuffer(this.response);
```

**Comment by IstoraMandiri** [comment]
Thanks @enjikaka, I managed to figure out the API from looking at the code but others might find it useful!

Excellent lib btw, I tried a few different options and this one creates the nicest looking waveforms.

Btw, it might be cool to extend with a way to output PNG as well as SVG?

**Comment by enjikaka** [comment]
@hitchcott The first version of this outputted PNG. I'll put support for PNG in this version too soon! :)

**Comment by enjikaka** [comment]
Documentation and examples are now updated and possibility to generate PNG is added.

Thanks for your engagement @hitchcott

**Comment by IstoraMandiri** [comment]
Excellent work! Thanks @enjikaka
